[build]
  functions = "netlify/functions"  # Specify the correct directory for your functions
  # Remove the `publish` setting if you don't need static assets

[functions]
  node_bundler = "esbuild"  # Optional: if you're using esbuild for bundling
