[build]
  base = "/opt/build/repo"
  functions = "netlify/functions"  # Location of serverless functions
  publish = "build"  # Points to the directory where static files are output after build

[functions]
  node_bundler = "esbuild"  # Optional if you're using esbuild for bundling
